version: '3'
services:
  rasp-monitor:
    image: truongkutetk97/rasp-monitor:0.1
    container_name: rasp-monitor
    user: root
    environment:
      ENV_TLG_API_RASP_MON: "6084770511:AAEyGM-bxRcsgaWpguwswEsxzvGrbL0DBwM"
    volumes:
      - /home/pi/Rasp-Monitor/docker-folder/:/var/rasp-monitor