name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "Start integrate docker images"
    - run: echo "Event: ${{ github.event_name }}, OS: ${{ runner.os }}, branch:  ${{ github.ref }}, Repo: ${{ github.repository }}, Status: ${{ job.status }} "
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
