name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Start integrate docker images"
    - uses: actions/checkout@v3
    - run: export docker_image_tag=$(date +%s)
    - run: echo $docker_image_tag
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rasp-mon:$docker_image_tag
    - name: Packaging the docker image
      run: docker save -o /target.tar rasp-mon:$docker_image_tag
    - run: ls -al /target.tar
