name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Start integrate docker images"
    - uses: actions/checkout@v3
    - run: export docker_image_name=my-image-name:$(date +%s)
    - run: echo $docker_image_name
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $docker_image_name
    - name: Packaging the docker image
      run: docker save -o /target.tar $docker_image_name
    - run: ls -al /target.tar
